// Generated by CoffeeScript 1.6.3
(function() {
  window.PDJSobj = (function() {
    PDJSobj.version = "0.3.1";

    PDJSobj.prototype.logg = function(str) {
      if (this.logging) {
        return console.log(str);
      }
    };

    PDJSobj.prototype.req = function() {
      return this.req_count++;
    };

    function PDJSobj(params) {
      if (params == null) {
        params = {};
      }
      this.subdomain = params.subdomain;
      this.token = params.token;
      this.refresh = params.refresh || 60;
      this.refresh_in_ms = this.refresh * 1000;
      this.protocol = params.protocol || "https";
      this.server = params.server || "pagerduty.com";
      this.logging = params.logging;
      this.req_count = 1;
      this.api_version = "v1";
      this.logg("Initializing PDJSobj");
    }

    PDJSobj.prototype.no_success_function = function(json, callerparams) {
      this.logg("no success function defined for " + callerparams.res);
      return this.logg(json);
    };

    PDJSobj.prototype.error_function = function(err, callerparams) {
      this.logg("Error for " + callerparams.res);
      this.logg(err.status);
      return this.logg(err.responseText);
    };

    PDJSobj.prototype.api = function(params) {
      var _this = this;
      if (params == null) {
        params = {};
      }
      this.logg("Call to API: " + params.res);
      params.url = params.url || this.protocol + "://" + this.subdomain + "." + this.server + "/api/" + this.api_version + "/" + params.res;
      params.attempt = params.attempt || 0;
      params.headers = params.headers || {};
      params.contentType = "application/json";
      params.data = params.data || {};
      params.data.PDJSversion = PDJSobj.version;
      params.data.request_count = this.req();
      params.data.attempt = params.attempt++;
      this.logg("params.data:");
      this.logg(params.data);
      params.headers.Authorization = 'Token token=' + this.token;
      params.error = params.error || function(err) {
        return _this.error_function(err, params);
      };
      params.success = params.success || function(data) {
        return _this.no_success_function(data, params);
      };
      this.logg(params);
      return $.ajax(params);
    };

    PDJSobj.prototype.api_all = function(params, datasofar) {
      var _this = this;
      if (params == null) {
        params = {};
      }
      if (datasofar == null) {
        datasofar = [];
      }
      params.data = params.data || {};
      params.data.limit = 100;
      params.data.offset = params.data.offset || 0;
      params.final_success = params.final_success || function(data) {
        return _this.no_success_function(data, params);
      };
      params.incremental_success = params.incremental_success || function(data) {
        return 0;
      };
      params.success = function(data) {
        data.res = params.res;
        params.incremental_success(data[params.res]);
        datasofar = datasofar.concat(data[params.res]);
        window.datasofar = datasofar;
        window.d = data;
        if (data.total > data.limit + data.offset) {
          _this.logg("Getting more");
          params.data.offset += params.data.limit;
          return _this.api_all(params, datasofar);
        } else {
          _this.logg("All done");
          _this.logg(params);
          data[params.res] = datasofar;
          data.res = params.res;
          data.offset = 0;
          data.limit = data.total;
          _this.logg(data);
          return params.final_success(data);
        }
      };
      this.logg(params);
      return this.api(params);
    };

    return PDJSobj;

  })();

}).call(this);
