version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    executor: node
    steps:
      - run:
          name: Install NPM
          command: npm ci
      - run:
          name: Build packages
          command: npm run build
      - store_artifacts:
          path: dist
  lint:
    executor: node
    steps:
      - run:
          name: Lint
          command: npm run lint
  test:
    executor: node
    steps:
      - run:
          name: Test
          command: npm run test


workflows:
  build-and-test:
    jobs:
      - build
      - lint
      - test
